// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gre-card-redesign/ActiveRecall.tsx": () => import("../components/mockups/gre-card-redesign/ActiveRecall.tsx"),
  "./components/mockups/gre-card-redesign/Constellation.tsx": () => import("../components/mockups/gre-card-redesign/Constellation.tsx"),
  "./components/mockups/gre-card-redesign/Storyboard.tsx": () => import("../components/mockups/gre-card-redesign/Storyboard.tsx"),
  "./components/mockups/gre-variants/Coach.tsx": () => import("../components/mockups/gre-variants/Coach.tsx"),
  "./components/mockups/gre-variants/Feed.tsx": () => import("../components/mockups/gre-variants/Feed.tsx"),
  "./components/mockups/gre-variants/Library.tsx": () => import("../components/mockups/gre-variants/Library.tsx"),
  "./components/mockups/gre-variants/Quest.tsx": () => import("../components/mockups/gre-variants/Quest.tsx")
};
