// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/belt-progress/Current.tsx": () => import("../components/mockups/belt-progress/Current.tsx"),
  "./components/mockups/belt-progress/VariantA.tsx": () => import("../components/mockups/belt-progress/VariantA.tsx"),
  "./components/mockups/belt-progress/VariantB.tsx": () => import("../components/mockups/belt-progress/VariantB.tsx"),
  "./components/mockups/belt-progress/VariantC.tsx": () => import("../components/mockups/belt-progress/VariantC.tsx"),
  "./components/mockups/gre-card-polished/Editorial.tsx": () => import("../components/mockups/gre-card-polished/Editorial.tsx"),
  "./components/mockups/gre-card-polished/Refined.tsx": () => import("../components/mockups/gre-card-polished/Refined.tsx"),
  "./components/mockups/gre-card-redesign/ActiveRecall.tsx": () => import("../components/mockups/gre-card-redesign/ActiveRecall.tsx"),
  "./components/mockups/gre-card-redesign/Constellation.tsx": () => import("../components/mockups/gre-card-redesign/Constellation.tsx"),
  "./components/mockups/gre-card-redesign/Storyboard.tsx": () => import("../components/mockups/gre-card-redesign/Storyboard.tsx"),
  "./components/mockups/gre-variants/Coach.tsx": () => import("../components/mockups/gre-variants/Coach.tsx"),
  "./components/mockups/gre-variants/Feed.tsx": () => import("../components/mockups/gre-variants/Feed.tsx"),
  "./components/mockups/gre-variants/Library.tsx": () => import("../components/mockups/gre-variants/Library.tsx"),
  "./components/mockups/gre-variants/Quest.tsx": () => import("../components/mockups/gre-variants/Quest.tsx"),
  "./components/mockups/gre-app-layouts/CommandDeck.tsx": () => import("../components/mockups/gre-app-layouts/CommandDeck.tsx"),
  "./components/mockups/gre-app-layouts/FocusFlow.tsx": () => import("../components/mockups/gre-app-layouts/FocusFlow.tsx"),
  "./components/mockups/gre-app-layouts/MissionDeck.tsx": () => import("../components/mockups/gre-app-layouts/MissionDeck.tsx"),
  "./components/mockups/gre-app-layouts/MissionDeckBold.tsx": () => import("../components/mockups/gre-app-layouts/MissionDeckBold.tsx"),
  "./components/mockups/gre-app-layouts/MissionDeckTight.tsx": () => import("../components/mockups/gre-app-layouts/MissionDeckTight.tsx"),
  "./components/mockups/gre-app-layouts/TopRail.tsx": () => import("../components/mockups/gre-app-layouts/TopRail.tsx")
};
